// src/app/components/site-nav.component.ts
import { Component, HostListener, signal } from "@angular/core"

interface NavLink {
  label: string
  href: string
}

@Component({
  selector: "app-site-nav",
  standalone: true,
  template: `
    <header
      class="fixed inset-x-0 top-0 z-50 transition-all duration-500"
      [class.bg-transparent]="!scrolled()"
      [class.text-background]="!scrolled()"
      [style.background-color]="scrolled() ? 'color-mix(in oklab, var(--background) 85%, transparent)' : ''"
      [style.color]="scrolled() ? 'var(--foreground)' : ''"
      [style.box-shadow]="scrolled() ? '0 1px 0 0 var(--border)' : 'none'"
      [style.backdrop-filter]="scrolled() ? 'blur(12px)' : 'none'"
    >
      <nav class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10">
        <a href="#inicio" class="flex items-center gap-3" (click)="close()">
          <span class="flex h-10 w-10 items-center justify-center rounded-full border border-current">
            <span class="font-serif text-lg italic leading-none">V</span>
          </span>
          <span class="flex flex-col leading-none">
            <span class="font-serif text-lg tracking-[0.16em]">VALDEOSO</span>
            <span class="text-[0.6rem] font-semibold tracking-[0.38em] opacity-70">
              CENTRO VETERINARIO
            </span>
          </span>
        </a>

        <ul class="hidden items-center gap-9 text-sm tracking-wide md:flex">
          @for (link of links; track link.href) {
            <li>
              <a [href]="link.href" class="relative py-1 transition-opacity hover:opacity-70">
                {{ link.label }}
              </a>
            </li>
          }
        </ul>

        <a
          href="#contacto"
          class="hidden rounded-full px-6 py-2.5 text-sm font-semibold tracking-wide transition-all duration-300 md:inline-flex"
          [style.background-color]="scrolled() ? 'var(--primary)' : 'color-mix(in oklab, var(--background) 90%, transparent)'"
          [style.color]="scrolled() ? 'var(--primary-foreground)' : 'var(--foreground)'"
        >
          Pedir cita
        </a>

        <button
          type="button"
          class="md:hidden"
          [attr.aria-label]="open() ? 'Cerrar menú' : 'Abrir menú'"
          (click)="toggle()"
        >
          @if (open()) {
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          } @else {
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>
          }
        </button>
      </nav>

      @if (open()) {
        <div class="border-t border-border bg-background text-foreground md:hidden">
          <ul class="flex flex-col px-6 py-4">
            @for (link of links; track link.href) {
              <li>
                <a [href]="link.href" (click)="close()" class="block py-3 text-base">
                  {{ link.label }}
                </a>
              </li>
            }
            <li>
              <a
                href="#contacto"
                (click)="close()"
                class="mt-2 inline-flex rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground"
              >
                Pedir cita
              </a>
            </li>
          </ul>
        </div>
      }
    </header>
  `,
})
export class SiteNavComponent {
  readonly links: NavLink[] = [
    { label: "Servicios", href: "#servicios" },
    { label: "Horario", href: "#horario" },
    { label: "Planes", href: "#planes" },
    { label: "Contacto", href: "#contacto" },
  ]

  readonly scrolled = signal(false)
  readonly open = signal(false)

  @HostListener("window:scroll")
  onScroll(): void {
    this.scrolled.set(window.scrollY > 40)
  }

  toggle(): void {
    this.open.update((v) => !v)
  }

  close(): void {
    this.open.set(false)
  }
}

// components/site-nav.tsx
"use client"

import { useEffect, useState } from "react"
import { Menu, X } from "lucide-react"
import { cn } from "@/lib/utils"

const links = [
  { label: "Filosofía", href: "#filosofia" },
  { label: "Método", href: "#metodo" },
  { label: "Cuidados", href: "#cuidados" },
  { label: "Reseñas", href: "#resenas" },
]

function Logo({ className }: { className?: string }) {
  return (
    <a href="#inicio" className={cn("flex items-center gap-3", className)}>
      <span className="flex h-10 w-10 items-center justify-center rounded-full border border-current">
        <span className="font-serif text-lg italic leading-none">N</span>
      </span>
      <span className="flex flex-col leading-none">
        <span className="font-serif text-xl tracking-[0.18em]">NAKOA</span>
        <span className="text-[0.6rem] font-medium tracking-[0.42em] opacity-70">
          ANIMAL
        </span>
      </span>
    </a>
  )
}

export function SiteNav() {
  const [scrolled, setScrolled] = useState(false)
  const [open, setOpen] = useState(false)

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40)
    onScroll()
    window.addEventListener("scroll", onScroll, { passive: true })
    return () => window.removeEventListener("scroll", onScroll)
  }, [])

  return (
    <header
      className={cn(
        "fixed inset-x-0 top-0 z-50 transition-all duration-500",
        scrolled
          ? "bg-background/85 text-foreground shadow-[0_1px_0_0_var(--border)] backdrop-blur-md"
          : "bg-transparent text-background",
      )}
    >
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10">
        <Logo />

        <ul className="hidden items-center gap-9 text-sm tracking-wide md:flex">
          {links.map((link) => (
            <li key={link.href}>
              <a
                href={link.href}
                className="relative py-1 transition-opacity hover:opacity-70"
              >
                {link.label}
              </a>
            </li>
          ))}
        </ul>

        <a
          href="#reserva"
          className={cn(
            "hidden rounded-full px-6 py-2.5 text-sm font-medium tracking-wide transition-all duration-300 md:inline-flex",
            scrolled
              ? "bg-primary text-primary-foreground hover:bg-accent"
              : "bg-background/90 text-foreground hover:bg-background",
          )}
        >
          Reserva tu cita
        </a>

        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-label={open ? "Cerrar menú" : "Abrir menú"}
          className="md:hidden"
        >
          {open ? <X className="size-6" /> : <Menu className="size-6" />}
        </button>
      </nav>

      {open && (
        <div className="border-t border-border bg-background text-foreground md:hidden">
          <ul className="flex flex-col px-6 py-4">
            {links.map((link) => (
              <li key={link.href}>
                <a
                  href={link.href}
                  onClick={() => setOpen(false)}
                  className="block py-3 text-base"
                >
                  {link.label}
                </a>
              </li>
            ))}
            <li>
              <a
                href="#reserva"
                onClick={() => setOpen(false)}
                className="mt-2 inline-flex rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground"
              >
                Reserva tu cita
              </a>
            </li>
          </ul>
        </div>
      )}
    </header>
  )
}
